### ISSUE TITLE
wıdget

### ISSUE THREAD

**Issue by VB10** [furkanagess/elements_app#31]
https://github.com/furkanagess/elements_app/blob/b84f70771dad4eed2c87cd02b248280fc3351855/lib/feature/view/info/info_view.dart#L35

widgtleri parse edip function componetleri sileim ve bu tarz provider ist r falan hepsini o congtexte okuyalım

**Comment by furkanagess** [comment]
You can check the issue you mentioned from the branch opened with the same issue number. Thanks for helping.
